package com.footystars.foot8.utils;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import static com.footystars.foot8.utils.CountriesUtil.*;
import static com.footystars.foot8.utils.ParameterName.CUP;
import static com.footystars.foot8.utils.ParameterName.LEAGUE;
import static com.footystars.foot8.utils.ParameterName.WORLD;

@Getter
@RequiredArgsConstructor
public enum TopLeagues {

    PREMIER_LEAGUE(39L, ParameterName.PREMIER_LEAGUE, ENGLAND, LEAGUE),
    COMMUNITY_SHIELD(528L, ParameterName.COMMUNITY_SHIELD, ENGLAND, CUP),
    EFL_TROPHY(46L, ParameterName.EFL_TROPHY, ENGLAND, CUP),
    FA_CUP(45L, ParameterName.FA_CUP, ENGLAND, CUP),
    PREMIER_LEAGUE_CUP(871L, ParameterName.PREMIER_LEAGUE_CUP, ENGLAND, CUP),
    FA_TROPHY(47L, ParameterName.FA_TROPHY, ENGLAND, CUP),
    LIGUE_1(61L, ParameterName.LIGUE_1, FRANCE, LEAGUE),
    COUPE_DE_FRANCE(66L, ParameterName.COUPE_DE_FRANCE, FRANCE, CUP),
    TROPHEE_DES_CHAMPIONS(526L, ParameterName.TROPHEE_DES_CHAMPIONS, FRANCE, CUP),
    SERIE_A(135L, ParameterName.SERIE_A, ITALY, LEAGUE),
    COPPA_ITALIA(137L, ParameterName.COPPA_ITALIA, ITALY, CUP),
    SUPER_CUP_ITALY(547L, ParameterName.SUPER_CUP_ITALY, ITALY, CUP),
    SUPER_CUP_PRIMAVERA(817L, ParameterName.SUPER_CUP_PRIMAVERA, ITALY, CUP),
    BUNDESLIGA(78L, ParameterName.BUNDESLIGA, GERMANY, LEAGUE),
    DFB_POKAL(81L, ParameterName.DFB_POKAL, GERMANY, CUP),
    SUPER_CUP_GERMANY(529L, ParameterName.SUPER_CUP_GERMANY, GERMANY, CUP),
    LA_LIGA(140L, ParameterName.LA_LIGA, SPAIN, LEAGUE),
    JUPILER_PRO_LEAGUE(144L, ParameterName.LA_LIGA, BELGIUM, LEAGUE),
    COPA_DEL_REY(143L, ParameterName.COPA_DEL_REY, SPAIN, CUP),

    // Add new leagues
    EKSTRAKLASA(106L, ParameterName.EKSTRAKLASA, "Poland", LEAGUE),
    SUPERLIGA(119L, ParameterName.SUPERLIGA, "Denmark", LEAGUE),
    SUPER_LEAGUE(207L, ParameterName.SUPER_LEAGUE, "Switzerland", LEAGUE),
    WORLD_CUP(1L, ParameterName.WORLD_CUP, WORLD, CUP),
    EURO_CHAMPIONSHIP(4L, ParameterName.EURO_CHAMPIONSHIP, WORLD, CUP),
    UEFA_NATIONS_LEAGUE(5L, ParameterName.UEFA_NATIONS_LEAGUE, WORLD, CUP),
    AFRICA_CUP_OF_NATIONS(6L, ParameterName.AFRICA_CUP_OF_NATIONS, WORLD, CUP),
    FRIENDLIES(10L, ParameterName.FRIENDLIES, WORLD, CUP),
    FIFA_CLUB_WORLD_CUP(15L, ParameterName.FIFA_CLUB_WORLD_CUP, WORLD, CUP),
    AFRICAN_NATIONS_CHAMPIONSHIP(19L, ParameterName.AFRICAN_NATIONS_CHAMPIONSHIP, WORLD, CUP),
    INTERNATIONAL_CHAMPIONS_CUP(26L, ParameterName.INTERNATIONAL_CHAMPIONS_CUP, WORLD, CUP),
    WORLD_CUP_QUALIFICATION_AFRICA(29L, ParameterName.WORLD_CUP_QUALIFICATION_AFRICA, WORLD, CUP),
    WORLD_CUP_QUALIFICATION_ASIA(30L, ParameterName.WORLD_CUP_QUALIFICATION_ASIA, WORLD, CUP),
    WORLD_CUP_QUALIFICATION_CONCACAF(31L, ParameterName.WORLD_CUP_QUALIFICATION_CONCACAF, WORLD, CUP),
    WORLD_CUP_QUALIFICATION_EUROPE(32L, ParameterName.WORLD_CUP_QUALIFICATION_EUROPE, WORLD, CUP),
    WORLD_CUP_QUALIFICATION_OCEANIA(33L, ParameterName.WORLD_CUP_QUALIFICATION_OCEANIA, WORLD, CUP),
    WORLD_CUP_QUALIFICATION_SOUTH_AMERICA(34L, ParameterName.WORLD_CUP_QUALIFICATION_SOUTH_AMERICA, WORLD, CUP),
    ASIAN_CUP_QUALIFICATION(35L, ParameterName.ASIAN_CUP_QUALIFICATION, WORLD, CUP),
    AFRICA_CUP_OF_NATIONS_QUALIFICATION(36L, ParameterName.AFRICA_CUP_OF_NATIONS_QUALIFICATION, WORLD, CUP),
    WORLD_CUP_QUALIFICATION_INTERCONTINENTAL_PLAY_OFFS(37L, ParameterName.WORLD_CUP_QUALIFICATION_INTERCONTINENTAL_PLAY_OFFS, WORLD, CUP),
    LEAGUE_CUP(48L, ParameterName.LEAGUE_CUP, ENGLAND, CUP),
    COUPE_DE_LA_LIGUE(65L, ParameterName.COUPE_DE_LA_LIGUE, FRANCE, CUP),
    EREDIVISIE(88L, ParameterName.EREDIVISIE, "Netherlands", LEAGUE),
    KNVB_BEKER(90L, ParameterName.KNVB_BEKER, "Netherlands", CUP),
    PRIMEIRA_LIGA(94L, ParameterName.PRIMEIRA_LIGA, "Portugal", LEAGUE),
    TACA_DE_PORTUGAL(96L, ParameterName.TACA_DE_PORTUGAL, "Portugal", CUP),
    TACA_DA_LIGA(97L, ParameterName.TACA_DA_LIGA, "Portugal", CUP),
    CUP_POLAND(108L, ParameterName.CUP_POLAND, "Poland", CUP),
    DBU_POKALEN(121L, ParameterName.DBU_POKALEN, "Denmark", CUP),
    SUPER_LIG(203L, ParameterName.SUPER_LIG, "Turkey", LEAGUE),
    CUP_TURKEY(206L, ParameterName.CUP_TURKEY, "Turkey", CUP),
    SCHWEIZER_CUP(209L, ParameterName.SCHWEIZER_CUP, "Switzerland", CUP),
    MAJOR_LEAGUE_SOCCER(253L, ParameterName.MAJOR_LEAGUE_SOCCER, "USA", LEAGUE),
    US_OPEN_CUP(257L, ParameterName.US_OPEN_CUP, "USA", CUP),
    OLYMPICS_MEN(480L, ParameterName.OLYMPICS_MEN, WORLD, CUP),
    SUPER_CUP_NETHERLANDS(543L, ParameterName.SUPER_CUP_NETHERLANDS, "Netherlands", CUP),
    SUPER_CUP_POLAND(727L, ParameterName.SUPER_CUP_POLAND, "Poland", CUP),
    CONMEBOL_UEFA_FINALISSIMA(913L, ParameterName.CONMEBOL_UEFA_FINALISSIMA, WORLD, CUP),
    EMIRATES_CUP(937L, ParameterName.EMIRATES_CUP, WORLD, CUP),
    KINGS_CUP(1038L, ParameterName.KINGS_CUP, WORLD, CUP),
    UEFA_CHAMPIONS_LEAGUE(2L, ParameterName.UEFA_CHAMPIONS_LEAGUE, WORLD, CUP),
    UEFA_EUROPA_LEAGUE(3L, ParameterName.UEFA_EUROPA_LEAGUE, WORLD, CUP),
    UEFA_SUPER_CUP(531L, ParameterName.UEFA_SUPER_CUP, WORLD, CUP),
    UEFA_CONFERENCE_LEAGUE(848L, ParameterName.UEFA_CONFERENCE_LEAGUE, WORLD, CUP);

    private final Long id;
    private final String leagueName;
    private final String country;
    private final String type;

    public static List<Long> getTopLeaguesIds() {
        return Arrays.stream(TopLeagues.values()).map(TopLeagues::getId)
                .collect(Collectors.toList());
    }
}
