package com.footystars.foot8.mapper;

import com.footystars.foot8.api.model.teams.statistics.statistic.TeamStatisticApi;
import com.footystars.foot8.business.model.entity.TeamStats;
import com.footystars.foot8.business.model.dto.TeamStatsDto;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.mapstruct.ReportingPolicy;

@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, componentModel = MappingConstants.ComponentModel.SPRING)
public interface TeamStatsMapper {


    TeamStats toEntity(TeamStatsDto teamStatsDto);

    @Mapping(source = "biggest.biggestGoals.goalsFor.home", target = "biggestGoalsForHome")
    @Mapping(source = "biggest.biggestGoals.goalsFor.away", target = "biggestGoalsForAway")
    @Mapping(source = "biggest.biggestGoals.against.home", target = "biggestGoalsAgainstHome")
    @Mapping(source = "biggest.biggestGoals.against.away", target = "biggestGoalsAgainstAway")
    @Mapping(source = "biggest.wins.home", target = "biggestWinHome")
    @Mapping(source = "biggest.wins.home", target = "biggestWinAway")
    @Mapping(source = "biggest.loses.away", target = "biggestLostHome")
    @Mapping(source = "biggest.loses.away", target = "biggestLostAway")
    @Mapping(source = "biggest.streak.draws", target = "biggestStreakDraws")
    @Mapping(source = "biggest.streak.loses", target = "biggestStreakLoses")
    @Mapping(source = "biggest.streak.wins", target = "biggestStreakWins")
    @Mapping(source = "cards.red.from0To15.percentage", target = "redCardFrom0To15Percentage")
    @Mapping(source = "cards.red.from0To15.total", target = "redCardFrom0To15Total")
    @Mapping(source = "cards.red.from16To30.percentage", target = "redCardFrom16To30Percentage")
    @Mapping(source = "cards.red.from16To30.total", target = "redCardFrom16To30Total")
    @Mapping(source = "cards.red.from31To45.percentage", target = "redCardFrom31To45Percentage")
    @Mapping(source = "cards.red.from31To45.total", target = "redCardFrom31To45Total")
    @Mapping(source = "cards.red.from46To60.percentage", target = "redCardFrom46To60Percentage")
    @Mapping(source = "cards.red.from46To60.total", target = "redCardFrom46To60Total")
    @Mapping(source = "cards.red.from61To75.percentage", target = "redCardFrom61To75Percentage")
    @Mapping(source = "cards.red.from61To75.total", target = "redCardFrom61To75Total")
    @Mapping(source = "cards.red.from76To90.percentage", target = "redCardFrom76To90Percentage")
    @Mapping(source = "cards.red.from76To90.total", target = "redCardFrom76To90Total")
    @Mapping(source = "cards.red.from91To105.percentage", target = "redCardFrom91To105Percentage")
    @Mapping(source = "cards.red.from91To105.total", target = "redCardFrom91To105Total")
    @Mapping(source = "cards.red.from106To120.percentage", target = "redCardFrom106To120Percentage")
    @Mapping(source = "cards.red.from106To120.total", target = "redCardFrom106To120Total")
    @Mapping(source = "cards.yellow.from0To15.percentage", target = "yellowCardFrom0To15Percentage")
    @Mapping(source = "cards.yellow.from0To15.total", target = "yellowCardFrom0To15Total")
    @Mapping(source = "cards.yellow.from16To30.percentage", target = "yellowCardFrom16To30Percentage")
    @Mapping(source = "cards.yellow.from16To30.total", target = "yellowCardFrom16To30Total")
    @Mapping(source = "cards.yellow.from31To45.percentage", target = "yellowCardFrom31To45Percentage")
    @Mapping(source = "cards.yellow.from31To45.total", target = "yellowCardFrom31To45Total")
    @Mapping(source = "cards.yellow.from46To60.percentage", target = "yellowCardFrom46To60Percentage")
    @Mapping(source = "cards.yellow.from46To60.total", target = "yellowCardFrom46To60Total")
    @Mapping(source = "cards.yellow.from61To75.percentage", target = "yellowCardFrom61To75Percentage")
    @Mapping(source = "cards.yellow.from61To75.total", target = "yellowCardFrom61To75Total")
    @Mapping(source = "cards.yellow.from76To90.percentage", target = "yellowCardFrom76To90Percentage")
    @Mapping(source = "cards.yellow.from76To90.total", target = "yellowCardFrom76To90Total")
    @Mapping(source = "cards.yellow.from91To105.percentage", target = "yellowCardFrom91To105Percentage")
    @Mapping(source = "cards.yellow.from91To105.total", target = "yellowCardFrom91To105Total")
    @Mapping(source = "cards.yellow.from106To120.percentage", target = "yellowCardFrom106To120Percentage")
    @Mapping(source = "cards.yellow.from106To120.total", target = "yellowCardFrom106To120Total")
    @Mapping(source = "cleanSheet.home", target = "cleanSheetsHome")
    @Mapping(source = "cleanSheet.away", target = "cleanSheetsAway")
    @Mapping(source = "cleanSheet.total", target = "cleanSheetsTotal")
    @Mapping(source = "failedToScore.home", target = "failedToScoreHome")
    @Mapping(source = "failedToScore.away", target = "failedToScoreAway")
    @Mapping(source = "failedToScore.total", target = "failedToScoreTotal")
    @Mapping(source = "goals.goalsFor.average.home", target = "goalsScoredAverageHome")
    @Mapping(source = "goals.goalsFor.average.away", target = "goalsScoredAverageAway")
    @Mapping(source = "goals.goalsFor.average.total", target = "goalsScoredAverageTotal")
    @Mapping(source = "goals.goalsFor.minute.from0To15.percentage", target = "goalsScoredFrom0To15Percentage")
    @Mapping(source = "goals.goalsFor.minute.from0To15.total", target = "goalsScoredFrom0To15Total")
    @Mapping(source = "goals.goalsFor.minute.from16To30.percentage", target = "goalsScoredFrom16To30Percentage")
    @Mapping(source = "goals.goalsFor.minute.from16To30.total", target = "goalsScoredFrom16To30Total")
    @Mapping(source = "goals.goalsFor.minute.from31To45.percentage", target = "goalsScoredFrom31To45Percentage")
    @Mapping(source = "goals.goalsFor.minute.from31To45.total", target = "goalsScoredFrom31To45Total")
    @Mapping(source = "goals.goalsFor.minute.from46To60.percentage", target = "goalsScoredFrom46To60Percentage")
    @Mapping(source = "goals.goalsFor.minute.from46To60.total", target = "goalsScoredFrom46To60Total")
    @Mapping(source = "goals.goalsFor.minute.from61To75.percentage", target = "goalsScoredFrom61To75Percentage")
    @Mapping(source = "goals.goalsFor.minute.from61To75.total", target = "goalsScoredFrom61To75Total")
    @Mapping(source = "goals.goalsFor.minute.from76To90.percentage", target = "goalsScoredFrom76To90Percentage")
    @Mapping(source = "goals.goalsFor.minute.from76To90.total", target = "goalsScoredFrom76To90Total")
    @Mapping(source = "goals.goalsFor.minute.from91To105.percentage", target = "goalsScoredFrom91To105Percentage")
    @Mapping(source = "goals.goalsFor.minute.from91To105.total", target = "goalsScoredFrom91To105Total")
    @Mapping(source = "goals.goalsFor.minute.from106To120.percentage", target = "goalsScoredFrom106To120Percentage")
    @Mapping(source = "goals.goalsFor.minute.from106To120.total", target = "goalsScoredFrom106To120Total")
    @Mapping(source = "goals.goalsFor.total.home", target = "goalsScoredTotalHome")
    @Mapping(source = "goals.goalsFor.total.away", target = "goalsScoredTotalAway")
    @Mapping(source = "goals.against.average.home", target = "goalsConcededAverageHome")
    @Mapping(source = "goals.against.average.away", target = "goalsConcededAverageAway")
    @Mapping(source = "goals.against.average.total", target = "goalsConcededAverageTotal")
    @Mapping(source = "goals.against.minute.from0To15.total", target = "goalsConcededFrom0To15Total")
    @Mapping(source = "goals.against.minute.from0To15.percentage", target = "goalsConcededFrom0To15Percentage")
    @Mapping(source = "goals.against.minute.from16To30.total", target = "goalsConcededFrom16To30Total")
    @Mapping(source = "goals.against.minute.from16To30.percentage", target = "goalsConcededFrom16To30Percentage")
    @Mapping(source = "goals.against.minute.from31To45.total", target = "goalsConcededFrom31To45Percentage")
    @Mapping(source = "goals.against.minute.from31To45.total", target = "goalsConcededFrom31To45Total")
    @Mapping(source = "goals.against.minute.from46To60.percentage", target = "goalsConcededFrom46To60Percentage")
    @Mapping(source = "goals.against.minute.from46To60.total", target = "goalsConcededFrom46To60Total")
    @Mapping(source = "goals.against.minute.from61To75.percentage", target = "goalsConcededFrom61To75Percentage")
    @Mapping(source = "goals.against.minute.from61To75.total", target = "goalsConcededFrom61To75Total")
    @Mapping(source = "goals.against.minute.from76To90.percentage", target = "goalsConcededFrom76To90Percentage")
    @Mapping(source = "goals.against.minute.from76To90.total", target = "goalsConcededFrom76To90Total")
    @Mapping(source = "goals.against.minute.from91To105.percentage", target = "goalsConcededFrom91To105Percentage")
    @Mapping(source = "goals.against.minute.from91To105.total", target = "goalsConcededFrom91To105Total")
    @Mapping(source = "goals.against.minute.from106To120.percentage", target = "goalsConcededFrom106To120Percentage")
    @Mapping(source = "goals.against.minute.from106To120.total", target = "goalsConcededFrom106To120Total")
    @Mapping(source = "goals.against.total.home", target = "goalsConcededTotalHome")
    @Mapping(source = "goals.against.total.away", target = "goalsConcededTotalAway")
    @Mapping(source = "fixtures.draws.home", target = "drawsHome")
    @Mapping(source = "fixtures.draws.away", target = "drawsAway")
    @Mapping(source = "fixtures.draws.total", target = "drawsTotal")
    @Mapping(source = "fixtures.loses.total", target = "losesHome")
    @Mapping(source = "fixtures.loses.home", target = "losesAway")
    @Mapping(source = "fixtures.loses.away", target = "losesTotal")
    @Mapping(source = "fixtures.played.total", target = "playedTotal")
    @Mapping(source = "fixtures.played.home", target = "playedHome")
    @Mapping(source = "fixtures.played.away", target = "playedAway")
    @Mapping(source = "fixtures.wins.home", target = "winsHome")
    @Mapping(source = "fixtures.wins.away", target = "winsAway")
    @Mapping(source = "fixtures.wins.total", target = "winsTotal")
    @Mapping(source = "league.leagueId", target = "leagueId")
    @Mapping(source = "league.leagueName", target = "leagueName")
    @Mapping(source = "league.leagueLogo", target = "leagueLogo")
    @Mapping(source = "league.country", target = "country")
    @Mapping(source = "league.year", target = "seasonYear")
    @Mapping(source = "penalty.total", target = "penaltiesTotal")
    @Mapping(source = "penalty.missed.percentage", target = "penaltiesMissedPercentage")
    @Mapping(source = "penalty.missed.total", target = "penaltiesMissedTotal")
    @Mapping(source = "penalty.scored.percentage", target = "penaltiesScoredTotal")
    @Mapping(source = "penalty.scored.total", target = "penaltiesScoredPercentage")
    @Mapping(source = "team.id", target = "clubId")
    @Mapping(source = "team.logo", target = "clubLogo")
    @Mapping(source = "team.name", target = "clubName")
    TeamStatsDto toDto(TeamStatisticApi teamStatistic);




    TeamStatsDto toDto(TeamStats teamStats);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    TeamStats partialUpdate(TeamStatsDto teamStatsDto, @MappingTarget TeamStats teamStats);
}